#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"


function gen_makeinc()
{
  makefile_in="${DIR}/CanteraPFR/Makefile.in"

  echo "********************************************************************"
  echo "Creating ${makefile_in}"
  echo "# File generated by get_cantera.sh." > ${makefile_in}
  echo "EXTERNAL := $1" >> ${makefile_in}
  echo "OPTIONS  := $2" >> ${makefile_in}

  echo "********************************************************************"
  echo "Appending ~/.bashrc"
  echo ${LD_LIBRARY_PATH} | grep -q "$1"
  if [[ "$?" != "0" ]]; then
    echo "export LD_LIBRARY_PATH=\"$1/lib:\${LD_LIBRARY_PATH}\"" >> ~/.bashrc
  else
    echo "Already in LD_LIBRARY_PATH: $1"
  fi

}


function header()
{
  echo "********************************************************************"
  echo "Running from $1"
  echo "Installing to $2"
}


function build_cantera()
{
  uname_out="$(uname -s)"

  echo "********************************************************************"
  echo "Starting build"

  case "${uname_out}" in
      Linux*|Darwin*)
          machine_os=Nix
          prefix="${DIR}/external/${machine_os}"
          cxx_flags="-g -O3 -std=c++11"

          header "${machine_os}" "${prefix}"
          gen_makeinc "${prefix}" "${cxx_flags}"

          scons build \
              prefix=${prefix} \
              python_package="none" \
              f90_interface="n" \
              system_eigen="n" \
              system_fmt="n" \
              system_googletest="n" \
              system_sundials="n" \
              blas_lapack_libs="openblas" \
              cxx_flags="${cxx_flags}";
          ;;
      CYGWIN*|MINGW*)
          machine_os=Win
          cxx_flags="-g -O3 -std=c++11 -U__STRICT_ANSI__"
          ;;
      *)
          echo "Unsupported system: ${uname_out}"
          exit -1
  esac

  scons test
  scons install
}


function get_cantera()
{
  echo "********************************************************************"
  echo "Trying to retrieve Cantera"
  git clone --recursive https://github.com/Cantera/cantera.git
  cd cantera
  git checkout tags/v2.4.0
  git submodule update

  build_cantera

  echo "Now run 'source ~/.bashrc' to refresh environment"
}

get_cantera
